In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier

In [3]:
df_train = pd.read_csv(r'C:\Users\am216\Downloads\fraudTrain.csv')
df_test = pd.read_csv(r'C:\Users\am216\Downloads\fraudTest.csv')

In [4]:
df = pd.concat([df_train, df_test])
df.shape[0]

1852394

In [5]:
numeric_columns = [i for i in df.columns if df[i].dtype == 'int64' or df[i].dtype =='int32' or df[i].dtype =='float64']
categorical_columns = [i for i in df.columns if df[i].dtype == 'object']

In [6]:
encoder = LabelEncoder()
for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col])
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,0,2703186189652095,514,8,4.97,164,18,0,576,...,36.0788,-81.1781,3495,372,791,80326,1325376018,36.011293,-82.048315,0
1,1,1,630423337322,241,4,107.23,312,161,0,439,...,48.8878,-118.2105,149,431,619,227462,1325376044,49.159047,-118.186462,0
2,2,2,38859492057661,390,0,220.11,116,386,1,610,...,42.1808,-112.2620,4154,308,309,1169030,1325376051,43.150704,-112.154481,0
3,3,3,3534093764340240,360,2,45.00,165,468,1,945,...,46.2306,-112.1138,1939,330,405,777909,1325376076,47.034331,-112.561071,0
4,4,4,375534208663984,297,9,41.96,339,153,1,422,...,38.4207,-79.4629,99,116,746,1186866,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,1819546,30560609640617,507,5,43.77,245,323,1,573,...,40.4931,-91.8912,519,477,386,1122239,1388534347,39.946837,-91.333331,0
555715,555715,1819547,3556613125071656,264,7,111.84,180,438,1,583,...,29.0393,-95.4401,28739,207,961,235369,1388534349,29.661049,-96.186633,0
555716,555716,1819548,6011724471098086,496,7,86.88,19,243,0,138,...,46.1966,-118.9017,3684,307,669,783898,1388534355,46.658340,-119.715054,0
555717,555717,1819549,4079773899158,75,13,7.99,120,351,1,711,...,44.6255,-116.4493,129,63,383,145946,1388534364,44.470525,-117.080888,0
555718,555718,1819550,4170689372027579,125,0,38.13,293,148,1,838,...,35.6665,-97.4798,116001,289,873,169136,1388534374,36.210097,-97.036372,0

In [7]:
columns = df.columns.tolist() 
columns.remove('is_fraud')

X = df.drop(['is_fraud'], axis=1)
y = df['is_fraud']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [9]:
corr_matrix = df.corr().abs()

In [13]:
import numpy as np
rs = np.random.RandomState(0)

corr = df.corr().abs()
corr.style.background_gradient(cmap='coolwarm')
# 'RdBu_r', 'BrBG_r', & PuOr_r are other good diverging colormaps

In [14]:
# Select upper triangle of correlation matrix
upper = corr.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

<ipython-input-14-c7537ecc5f9a>:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  upper = corr.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

In [15]:
# Find index of feature columns with correlation greater than 0.8
to_drop = [column for column in upper.columns if any(upper[column] > 0.8)]

# Drop highly correlated features
X.drop(X[to_drop], axis=1, inplace=True)

print(X)

        Unnamed: 0  trans_date_trans_time            cc_num  merchant  \
0                0                      0  2703186189652095       514
1                1                      1      630423337322       241
2                2                      2    38859492057661       390
3                3                      3  3534093764340240       360
4                4                      4   375534208663984       297
...            ...                    ...               ...       ...
555714      555714                1819546    30560609640617       507
555715      555715                1819547  3556613125071656       264
555716      555716                1819548  6011724471098086       496
555717      555717                1819549     4079773899158        75
555718      555718                1819550  4170689372027579       125

        category     amt  first  last  gender  street  city  state    zip  \
0              8    4.97    164    18       0     576   532     27  28654
1              4  107.23    312   161       0     439   619     47  99160
2              0  220.11    116   386       1     610   474     13  83252
3              2   45.00    165   468       1     945    84     26  59632
4              9   41.96    339   153       1     422   217     45  24433
...          ...     ...    ...   ...     ...     ...   ...    ...    ...
555714         5   43.77    245   323       1     573   471     24  63453
555715         7  111.84    180   438       1     583   427     43  77566
555716         7   86.88     19   243       0     138   110     47  99323
555717        13    7.99    120   351       1     711   508     13  83643
555718         0   38.13    293   148       1     838   239     36  73034

            lat  city_pop  job  dob  trans_num
0       36.0788      3495  372  791      80326
1       48.8878       149  431  619     227462
2       42.1808      4154  308  309    1169030
3       46.2306      1939  330  405     777909
4       38.4207        99  116  746    1186866
...         ...       ...  ...  ...        ...
555714  40.4931       519  477  386    1122239
555715  29.0393     28739  207  961     235369
555716  46.1966      3684  307  669     783898
555717  44.6255       129   63  383     145946
555718  35.6665    116001  289  873     169136

[1852394 rows x 18 columns]

In [16]:
X = df.drop(['is_fraud'], axis=1)
y = df['is_fraud']

X = df.drop(['is_fraud'], axis=1)
y = df['is_fraud']


scaler = StandardScaler()

X[columns] = scaler.fit_transform(X[columns])
df[X.columns] = X
df

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,-1.464098,-1.733596,-0.316766,0.850891,0.452162,-0.408741,-0.183377,-1.715579,-0.908554,0.283777,...,-0.485167,0.658263,-0.282429,0.848517,0.909287,-1.581835,-1.830067,-0.495080,0.594463,0
1,-1.464095,-1.733594,-0.318830,-0.506968,-0.570001,0.233378,1.319765,-0.677196,-0.908554,-0.197717,...,2.040531,-2.035415,-0.293527,1.266748,0.275196,-1.306681,-1.830065,2.080082,-2.031915,0
2,-1.464092,-1.733592,-0.318801,0.234134,-1.592163,0.942184,-0.670883,0.956622,1.100650,0.403272,...,0.718034,-1.602731,-0.280243,0.394843,-0.867643,0.454115,-1.830065,0.903268,-1.593535,0
3,-1.464090,-1.733590,-0.316131,0.084919,-1.081082,-0.157381,-0.173221,1.552058,1.100650,1.580648,...,1.516580,-1.591951,-0.287590,0.550794,-0.513731,-0.277308,-1.830063,1.663928,-1.623084,0
4,-1.464087,-1.733588,-0.318544,-0.228433,0.707702,-0.176470,1.593987,-0.735288,1.100650,-0.257464,...,-0.023388,0.783024,-0.293693,-0.966178,0.743391,0.487470,-1.830057,0.026642,0.842714,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,0.050477,1.729973,-0.318807,0.816074,-0.314460,-0.165105,0.639288,0.499153,1.100650,0.273233,...,0.385251,-0.120991,-0.292300,1.592826,-0.583776,0.366613,1.641110,0.275748,-0.080336,0
555715,0.050480,1.729974,-0.316114,-0.392570,0.196621,0.262326,-0.020875,1.334215,1.100650,0.308379,...,-1.873227,-0.379132,-0.198697,-0.321111,1.536005,-1.291894,1.641110,-1.738860,-0.433054,0
555716,0.050482,1.729976,-0.314239,0.761362,0.196621,0.105595,-1.656050,-0.081760,-0.908554,-1.255598,...,1.509876,-2.085692,-0.281802,0.387755,0.459525,-0.266108,1.641111,1.590285,-2.143007,0
555717,0.050485,1.729978,-0.318828,-1.332626,1.729865,-0.389777,-0.630257,0.702472,1.100650,0.758242,...,1.200084,-1.907308,-0.293593,-1.341877,-0.594836,-1.459121,1.641111,1.161773,-1.951567,0
555718,0.050488,1.729980,-0.315645,-1.083934,-1.592163,-0.200520,1.126794,-0.771595,1.100650,1.204591,...,-0.566465,-0.527497,0.090741,0.260159,1.211586,-1.415754,1.641112,-0.456142,-0.494810,0

In [17]:
from sklearn.model_selection import cross_val_score

In [20]:
from sklearn.model_selection import GridSearchCV

In [24]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]}

In [25]:
model_rfc = RandomForestClassifier(random_state=42, n_estimators=10, n_jobs=-1, max_depth=20)

In [27]:
grid_search = GridSearchCV(estimator=model_rfc, param_grid=param_grid, 
                           cv=5, n_jobs=-1, verbose=2)

grid_search.fit(X, y)

Fitting 2 folds for each of 216 candidates, totalling 432 fits

KeyboardInterrupt:

In [ ]:
y_pred = grid_search.predict(X_test)

# Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)

# Print the accuracy score
print(f'Accuracy Score: {accuracy}')

In [ ]:
# Print the best parameters and the best score
print(f"Best parameters: {grid_search.best_params_}")
print(f"Best cross-validation score: {grid_search.best_score_}")

In [19]:
scores = cross_val_score(model_rfc, X, y, cv=5)

# Print the cross-validation scores and the mean score
print(f"Cross-validation scores: {scores}")
print(f"Mean cross-validation score: {scores.mean()}")

Cross-validation scores: [0.00533094 0.71059088 0.41822883 0.56764621 0.99479051]
Mean cross-validation score: 0.539317475371351