In [130]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.ensemble import GradientBoostingClassifier
from imblearn.over_sampling import SMOTE

In [100]:
df = pd.read_csv('fraudTrain.csv')
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [104]:
df.drop(columns = "Unnamed: 0",inplace = True)

In [106]:
df.drop(columns = "dob",inplace = True)

In [108]:
df.drop(columns = "trans_date_trans_time",inplace = True)
df.drop(columns = "merchant",inplace = True)
df.drop(columns = "category",inplace = True)
df.drop(columns = "first",inplace = True)
df.drop(columns = "last",inplace = True)
df.drop(columns = "job",inplace = True)
df.drop(columns = "street",inplace = True)
df.drop(columns = "city",inplace = True)
df.drop(columns = "state",inplace = True)
df.drop(columns = "trans_num",inplace = True)
df.drop(columns = "long",inplace = True)
df.drop(columns = "merch_long",inplace = True)

In [110]:
 df=pd.get_dummies(df, columns=['gender'])

In [142]:
X = df.drop(['is_fraud'], axis=1)
y = df['is_fraud']

X = df.drop(['is_fraud'], axis=1)
y = df['is_fraud']

In [144]:
df.head()

,cc_num,amt,zip,lat,city_pop,unix_time,merch_lat,is_fraud,gender_F,gender_M
0,2703186189652095,4.97,28654,36.0788,3495,1325376018,36.011293,0,True,False
1,630423337322,107.23,99160,48.8878,149,1325376044,49.159047,0,True,False
2,38859492057661,220.11,83252,42.1808,4154,1325376051,43.150704,0,False,True
3,3534093764340240,45.00,59632,46.2306,1939,1325376076,47.034331,0,False,True
4,375534208663984,41.96,24433,38.4207,99,1325376186,38.674999,0,False,True

In [146]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [148]:
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

In [ ]:
# Select the top features using SelectKBest with chi-squared scores
k_best_features = SelectKBest(score_func=chi2, k=9)  # Adjust k as needed to be <= the number of features
X_train_best = k_best_features.fit_transform(X_train_smote, y_train_smote)
X_test_best = k_best_features.transform(X_test)



#k_best_features = SelectKBest(score_func=chi2, k=2)  # Select top 2 features

# Fit the SelectKBest model and transform X to get selected features
#X_best = k_best_features.fit_transform(X, y)

In [159]:
model_gbc = GradientBoostingClassifier(random_state=42, n_estimators=100, max_depth=3)
model_gbc.fit(X_train_best, y_train_smote)
# Create RandomForestClassifier model
# model_rfc = RandomForestClassifier(random_state=42, n_estimators=10, n_jobs=-1, max_depth=20)

# Fit the model
#model_gbc.fit(X_best, y)
#model_rfc.fit(X_best, y)

GradientBoostingClassifier(random_state=42)

In [172]:
y_pred = model_gbc.predict(X_test_best)

# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='weighted') 
#calculate precesion 
precision = precision_score(y_test, y_pred, average='weighted')  # or 'macro', 'micro', 'binary', depending on your use case

# Calculate recall score
recall = recall_score(y_test, y_pred, average='weighted')  # or 'macro', 'micro', 'binary', depending on your use case



#X_test = X_best  # Replace with your actual test data

# Predict probabilities
#y_pred_prob = model_gbc.predict_proba(X_test)

# Predict classes
#y_pred = model_gbc.predict(X_test)

# Print predictions
#print("Predicted probabilities:")
#print(y_pred_prob)

#print("\nPredicted classes:")
#print(y_pred)

In [174]:
print(f"Accuracy: {accuracy:.2f}")
print(f"F1 Score: {f1:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

Accuracy: 0.95
F1 Score: 0.97
Precision: 0.99
Recall: 0.95

In [ ]:
# Predict using the test set
y_pred = model_gbc.predict(X_best)

# Calculate accuracy score
accuracy = accuracy_score(y_true, y_pred)

# Calculate F1 score
f1 = f1_score(y_test, y_pred, average='weighted')  # or 'macro', 'micro', 'binary', depending on your use case

print(f"F1 Score: {f1:.2f}")

#print(f"Precision: {precision:.2f}")
#print(f"Recall: {recall:.2f}")